### ISSUE TITLE
filter button is in French

### ISSUE THREAD

**Issue by ajw725** [ayann/active_admin_flat_skin#12]
the rest of the code is in English, so it seems like this should be as well. in your js file, at line 14, you have this code:
```javascript
$('<a>').text('Afficher les filtres').attr({
  href: '#value', id:'diplay-filter'
})
```
the text() argument should be 'Display filters'. the id should probably be 'display-filter' instead of 'diplay-filter', too, but that doesn't really matter since it seems to be consistent.

**Comment by ajw725** [comment]
sorry - noticed that this has been fixed on master, just not released

**Comment by vernondegoede** [comment]
@ayann Can you create a new release? That should fix this.

**Comment by gslopez** [comment]
@ayann Yes please, create a new release !

**Comment by CanciuCostin** [comment]
You can update this in the Gemfile:
```
gem 'active_admin_flat_skin', github: 'ayann/active_admin_flat_skin'
```
