### ISSUE TITLE
Can't change colors of theme

### ISSUE THREAD

**Issue by TranBaVinhSon** [ayann/active_admin_flat_skin#18]
I try to change basic colors of the theme by placing `$skinActiveColor: #00d478;`. But it didn't work

**Comment by AnthonyLatty** [comment]
The issue is how you layout your active_admin.scss file. Place your overridden  styles before importing the core SASS file for active admin.

**Comment by liurui12w** [comment]
you can write app/assets/stylesheets/active_admin.scss.
$skinActiveColor: #2866b1 !default; #first

@import "active_admin_flat_skin";#second import
