### ISSUE TITLE
Add !default flag to all variables

### ISSUE THREAD

**Issue by goosys** [ayann/active_admin_flat_skin#5]
Thanks for the beautiful theme.

I would like to change $skinBlack variable and other.
Please add !default flag to all variables like this.

```SCSS
$skinBlack: rgb(55, 71, 79) !default;
$panelHeaderBck: $skinBlack !default;
$skinBlackLight: rgb(69, 90, 100) !default;
$textGray: rgb(174, 179, 181) !default;
```

**Comment by ayann** [comment]
Hello i added !default flag to defined variables

**Comment by goosys** [comment]
Thank you very much!
